#######################################
# Tasks file for the Arvados SSO role #
#######################################

- name: Install ruby bundle
  sudo: yes
  gem: name=bundler state=latest

- name: Install Arvados SSO server
  sudo: yes
  yum: name=arvados-sso-server state=latest

- name: Generate uuid prefix for the Single Sign On service
  shell: >
    ruby -e 'puts "#{rand(2**64).to_s(36)[0,5]}"'
  register: uuid_prefix_sso

- name: Generate secret token for the Single Sign On service
  shell: >
    ruby -e 'puts rand(2**400).to_s(36)'
  register: secret_token_sso

#- name: Add uuid and secret token to /etc/arvados/sso/application.yml
#  sudo: yes
#  template: src=application.j2 dest=/etc/arvados/sso/application.yml
