#######################################
# Tasks file for the Arvados SSO role #
#######################################

- name: Link Ruby 2.1.3 to be used system-wide
  sudo: yes
  shell: >
    ln -s -f /usr/local/rvm/rubies/ruby-2.1.3/bin/* /usr/bin

- name: Install rails (this may take a couple of minutes, pease be patient)
  sudo: yes
  gem: name=rails state=latest

- name: Link rails to be used system-wide
  sudo: yes
  shell: >
    ln -s -f /usr/local/rvm/gems/ruby-2.1.3/bin/rails /usr/bin/rails

- name: Install Arvados SSO server
  sudo: yes
  yum: name=arvados-sso-server state=latest

- name: Add uuid and secret token to /etc/arvados/sso/application.yml
  sudo: yes
  template: src=application.j2 dest=/etc/arvados/sso/application.yml

- name: Initialize PostgreSQL database
  sudo: yes
  command: service postgresql initdb
  when: ansible_distribution == "CentOS"
  args:
    creates: /var/lib/pgsql/data/postgresql.conf

- name: Start PostgreSQL
  sudo: yes
  service: name=postgresql state=started

# On CentOS6, you will need to modify PostgreSQL’s configuration to allow password authentication for local users
- name: Allow password authentication for local users (PostgreSQL)
  sudo: yes
  shell: >
    sudo sed -i -e "s/127.0.0.1\/32          ident/127.0.0.1\/32          md5/" /var/lib/pgsql/data/pg_hba.conf &&
    sudo sed -i -e "s/::1\/128               ident/::1\/128               md5/" /var/lib/pgsql/data/pg_hba.conf
  when: ansible_distribution == "CentOS"

- name: Restart Postgres initdb service
  sudo: yes
  service: name=postgresql state=restarted
  when: ansible_distribution == "CentOS"

- name: Modify /etc/arvados/sso/database.yml to use generated password
  sudo: yes
  template: src=database.j2 dest=/etc/arvados/sso/database.yml

- name: Install prerequisistes to create a new user in the database
  sudo: yes
  yum: name=python-psycopg2.x86_64
  when: ansible_distribution == "CentOS"

- name: Create a new postgresql user with permission to create its own databases.
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_user:
    name: arvados_sso
    password: "{{ db_password }}"
    encrypted: True
    role_attr_flags: NOCREATEROLE,NOSUPERUSER,CREATEDB

- name: Create database arvados_sso_production
  become: yes
  become_user: postgres
  become_method: sudo
  postgresql_db:
    name: arvados_sso_production
    encoding: UTF8
    owner: arvados_sso
    template: template0

# Yum reinstall is not exposed in ansible
- name: Reconfigure package
  sudo: yes
  shell: >
    yum reinstall arvados-sso-server -y

- name: Copy new-client script to /tmp
  template: src=new_client.j2 dest=/tmp/new_client.rb

- name: Create arvados-server client
  sudo: yes
  shell: >
    cd /var/www/arvados-sso/current/ &&
    rails runner -e production /tmp/new_client.rb
