sso_app_id: arvados-sso
sso_app_secret: wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
websocket_address: wss://ws.zzzzz.example.com/websocket
git_repositories_dir: /var/lib/arvados/git/repositories

SSL_CERT_PATH: /etc/nginx/ssl
puma_runit: /etc/sv/arvados-puma
