#######################################
# Tasks file for the Arvados API role #
#######################################

- name: Install Arvados API server and dependencies
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - bison
    - make
    - automake
    - gcc
    - gcc-c++
    - libcurl-devel
    - git
    - postgresql-server
    - postgresql-devel
    - python-psycopg2
    - arvados-api-server

- name: "Add Postgresql database credentials"
 include: postgresql.yml
 notify:
   - restart postgresql

- name: "Create arvados-api app and database config"
  file: path="/etc/arvados/api" state=directory mode=0700

- name: Copy API database config
  sudo: yes
  template: src=database.j2 dest=/etc/arvados/api/database.ym

- name: Copy API application config
  sudo: yes
  template: src=application.j2 dest=/etc/arvados/api/application.yml
  notify: restart nginx
