---
- name: see if the db got initialized
  stat: path=/var/lib/pgsql/data
  register: db_initialized

- name: initdb if not already created
  action: shell /etc/init.d/postgresql initdb
  ignore_errors: yes
  when: db_initialized.stat.exists == True
  notify:
    - restart postgresql

# On CentOS6, you will need to modify PostgreSQL’s configuration to allow password authentication for local users
- name: Allow password authentication for local users (PostgreSQL)
  shell: >
    sudo sed -i -e "s/ident/trust/" /var/lib/pgsql/data/pg_hba.conf
  when: ansible_distribution == "CentOS"
  notify:
    - restart postgresql

- name: Restart PostgreSQL
  sudo: yes
  service: name=postgresql state=restarted

- name: ensure database is created
  action: postgresql_db db={{dbname}}

- name: ensure user has access to database
  action: postgresql_user db={{dbname}} user={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure user does not have unnecessary privilege
  action: postgresql_user user={{dbuser}} role_attr_flags=NOCREATEROLE,NOSUPERUSER,CREATEDB
